Repository CheatSOL/CheatSOL-BE, pull requests merged in 2024-06, with the labels that each got.

#5 FEAT: 네이버 종목뉴스 크롤링 후 데이터베이스 저장 API 구현 완료
  .gitignore
  package.json
  src/controllers/NewsCrawling.js
  src/models/CompanyNews.js
  src/routes/index.js
  src/utils/NaverStockNews.js
Labels: ✨ Feature

#6 FEAT: DB에 기업 정보 넣어놓기
  src/controllers/AuthController.js
  src/controllers/CompanyController.js
  src/models/AuthToken.js
  src/models/Company.js
  src/models/HashTag.js
  src/routes/index.js
  src/utils/DtoUtils.js
  src/utils/KISUtils.js
Labels: ✨ Feature

#9 ✨Feat: 한국투자증권 외부 api를 사용하는 API 추가
  app.js
  src/controllers/AuthController.js
  src/controllers/NewsCrawling.js
  src/controllers/stockdetail/CurrentPrice.js
  src/controllers/stockdetail/DailyPrice.js
  src/models/AuthToken.js
  src/routes/index.js
  src/utils/KISUtils.js
Labels: ✨ Feature

#15 ✨Feat: 기업 상세 뉴스 탭 뉴스크롤링 로직 추가
  src/controllers/NewsCrawling.js
  src/routes/index.js
  src/utils/NaverStockNews.js
Labels: :recycle: refactor, :page_facing_up: task

#24 Feat/ 현재 검색어 구글 트랜드 api 및 기업 상세 정보 APi구현
  app.js
  package.json
  requirements.txt
  src/routes/google.js
  src/routes/stock.info.detail.js
Labels: :page_facing_up: task

#25 ✨Feat: 한투 실시간 데이터 웹소켓 통신 후 프론트엔드에게 데이터 전달
  app.js
  package.json
  src/controllers/stockdetail/DailyPrice.js
  src/routes/index.js
  src/utils/NaverStockNews.js
  src/utils/WSPrice.js
Labels: ✨ Feature, :page_facing_up: task

#26 ✨feat: 연관어 크롤링 및 프론트 API 연결 구현
  app.js
  package.json
  src/routes/keyword.js
Labels: ✨ Feature, :page_facing_up: task

#31 fix: 연관키워드 페이지 오류 수정
  requirements.txt
  src/routes/keyword.js
Labels: 🐛 fix

#33 🐛fix: WSPrice-approvalKeycache코드 추가
  src/utils/WSPrice.js
Labels: 🐛 fix

#36 Feat/ 구글 관심경향 차트 및 구글 뉴스 크롤링 api 구현완료
  app.js
  package.json
  src/routes/google-news.js
  src/routes/google.js
Labels: :page_facing_up: task

#39 Feat/ 유튜브 관심경향 차트 및 유튜브 데이터 크롤링 api 개발
  app.js
  package.json
  src/routes/socialChart.js
  src/routes/youtube-news.js
Labels: :page_facing_up: task

#44 Feat/ 네이버 관심경향 차트 및 네이버 뉴스 크롤링 api 개발
  app.js
  src/routes/naver-news.js
  src/routes/socialChart.js
  src/routes/youtube-news.js
Labels: :page_facing_up: task

#45 ✨feat: youtube-유튜브 크롤링 구현
  src/routes/youtube.js
  src/utils/Youtube.js
Labels: ✨ Feature

#50 FIX: bin/www - 이거 지우지 마세요!!
  bin/www
Labels: 🐛 fix

#53 FIX: app.js - error youtuberouter 안지워진거 수정
  app.js
Labels: 🐛 fix

#54 ✨feat: files - instagram 캐싱 적용
  src/routes/instagram-news.js
  src/routes/keyword.js
  src/routes/social.js
  src/routes/youtube-news.js
Labels: 🐛 fix, ✨ Feature

#55 🐛fix: app.js - instaNews 안나오는 현상 수정
  app.js
Labels: 🐛 fix

#56 ♻️ refactor: 네이버 데이터랩 키 값 env파일로 저장
  src/routes/socialChart.js
Labels: :page_facing_up: task

#57 FEAT: .env 추가로 인한 CICD 파이프라인 수정
  .github/workflows/main.yml
  src/routes/instagram-news.js
  src/scripts/get_similar_words.py
Labels: ✨ Feature

#59 Feat: AI 모델 캐싱 적용
  README.md
  src/controllers/social/google.js
  src/controllers/social/naver.js
  src/routes/company.js
  src/scripts/fast_word2vec_model.model
Labels: ✨ Feature
